"""empty message

Revision ID: a04cb532d908
Revises: f394a38f355e
Create Date: 2025-09-08 17:37:17.663163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04cb532d908'
down_revision = 'f394a38f355e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'system_users', ['assigned_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workshop_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_by')

    # ### end Alembic commands ###
