"""empty message

Revision ID: 1af64e4339be
Revises: 56948dd2bef6
Create Date: 2025-10-27 19:17:59.737419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af64e4339be'
down_revision = '56948dd2bef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True, comment='URL o identificador del avatar (predefinido o custom)'))
        batch_op.add_column(sa.Column('avatar_type', sa.String(length=20), nullable=True, comment='initials, predefined, custom, gravatar'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.drop_column('avatar_type')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
