"""empty message

Revision ID: ece612118cce
Revises: e8b50f0d1d4e
Create Date: 2025-09-04 00:14:24.834007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ece612118cce'
down_revision = 'e8b50f0d1d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('two_factor_last_used', sa.DateTime(), nullable=True))
    op.add_column('system_users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False, comment='Si el usuario tiene 2FA habilitado'))
    op.add_column('system_users', sa.Column('two_factor_secret', sa.String(length=64), nullable=True, comment='Secret Base32 para TOTP - SE ALMACENA EN BD LOCAL'))
    op.add_column('system_users', sa.Column('two_factor_enabled_at', sa.DateTime(), nullable=True))
    op.alter_column('system_users', 'auth_provider',
               existing_type=postgresql.ENUM('MICROSOFT', 'LOCAL', name='authprovider'),
               comment='Solo LOCAL por ahora, MICROSOFT para posible Fase 2',
               existing_comment='microsoft para staff, local para clientes',
               existing_nullable=False)
    op.alter_column('system_users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Solo para auth_provider=LOCAL',
               existing_comment='Solo para clientes con auth_provider=local',
               existing_nullable=True)
    op.alter_column('system_users', 'dni',
               existing_type=sa.VARCHAR(length=20),
               comment='DNI obligatorio para identificación',
               existing_comment='Solo para clientes',
               existing_nullable=False)
    op.drop_constraint('system_users_external_id_key', 'system_users', type_='unique')
    op.drop_column('system_users', 'external_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_users', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='ID de Microsoft para empleados o auth0'))
    op.create_unique_constraint('system_users_external_id_key', 'system_users', ['external_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('system_users', 'dni',
               existing_type=sa.VARCHAR(length=20),
               comment='Solo para clientes',
               existing_comment='DNI obligatorio para identificación',
               existing_nullable=False)
    op.alter_column('system_users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='Solo para clientes con auth_provider=local',
               existing_comment='Solo para auth_provider=LOCAL',
               existing_nullable=True)
    op.alter_column('system_users', 'auth_provider',
               existing_type=postgresql.ENUM('MICROSOFT', 'LOCAL', name='authprovider'),
               comment='microsoft para staff, local para clientes',
               existing_comment='Solo LOCAL por ahora, MICROSOFT para posible Fase 2',
               existing_nullable=False)
    op.drop_column('system_users', 'two_factor_enabled_at')
    op.drop_column('system_users', 'two_factor_secret')
    op.drop_column('system_users', 'two_factor_enabled')
    op.drop_column('audit_logs', 'two_factor_last_used')
    # ### end Alembic commands ###
