"""empty message

Revision ID: f300296e101f
Revises: 1af64e4339be
Create Date: 2025-10-27 22:49:13.101256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f300296e101f'
down_revision = '1af64e4339be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('avatar_style', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('avatar_color', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('avatar_seed', sa.String(length=100), nullable=True))
        batch_op.alter_column('avatar_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='initials, predefined, custom, gravatar',
               existing_nullable=True)
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='URL o identificador del avatar (predefinido o custom)'))
        batch_op.alter_column('avatar_type',
               existing_type=sa.VARCHAR(length=20),
               comment='initials, predefined, custom, gravatar',
               existing_nullable=True)
        batch_op.drop_column('avatar_seed')
        batch_op.drop_column('avatar_color')
        batch_op.drop_column('avatar_style')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
