"""empty message

Revision ID: f394a38f355e
Revises: 5ce666c764d9
Create Date: 2025-09-08 13:51:43.597520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f394a38f355e'
down_revision = '5ce666c764d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', postgresql.ENUM('MICROSOFT', 'LOCAL', name='authprovider'), autoincrement=False, nullable=False, comment='Solo LOCAL por ahora, MICROSOFT para posible Fase 2'))

    # ### end Alembic commands ###
